kind: pipeline
name: test

steps:
  - name: test
    image: golang:alpine
    when:
      branch:
        - master

  - name: docker
    image: plugins/docker
    settings:
      username: 
        from_secret: DRONE_DOCKER_USERNAME
      password: 
        from_secret: DRONE_DOCKER_PASSWORD
      repo: craig0213/test-drone
      debug: true

  - name: publish
    image: plugins/gcr
    settings:
      registry: asia.gcr.io
      repo: LoginTest/test-drone
      json_key: 
        from_secret: DRONE_GCR_JSON_KEY
